plugins:
  - module: Audio
    location: "Brian"
    config:
        sounds:
            beep: "/etc/sounds/ding1.wav"
            prefix: "/etc/sounds/login.wav"
            repeat: "/etc/sounds/cymbal.wav"
            postfix: "/etc/sounds/logout.wav"
        commands:
            init:
              - ["amixer", "cset", "numid=3", "1"]
              - ["amixer", "sset", "PCM", "100%"]
              - ["mpc", "repeat", "on"]
            play:
              - ["aplay", "-q", "{file}"]
            say:
              - ["speech", "{text}"]
            music_play:
              - ["mpc", "clear"]
              - ["mpc", "load", "{play_list}"]
              - ["mpc", "play"]
            music_stop:
              - ["mpc", "stop"]
            music_pause:
              - ["mpc", "pause-if-playing"]
            music_resume:
              - ["mpc", "play"]
  - module: LIFX
    location: "Brian"
    config:
        lights: ["Brian"]
  - module: MQTT
    location: "Brian"
    config: {}
